### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by cherokee93** [doudz/homeassistant-myjdownloader#1]
Hey doudz,
thanks for your myjdownloader integration.
Maybe i'm doing something wrong. It detects my instance but it says "Device not found" 
```
sensor:
  - platform: myjdownloader
    email: !secret mail
    password: !secret pwd2
```
![image](https://user-images.githubusercontent.com/12370126/71324851-7a3a3580-24e4-11ea-9d00-f1d4a9a47a5e.png)
