### ISSUE TITLE
Add device_id to the list of online devices

### ISSUE THREAD

**Issue by pooyashahidi** [doudz/homeassistant-myjdownloader#30]
Hi,

I would like to suggest adding the device id to the list of online devices.
I achieved this by modifying  the following part of sensor.py:
https://github.com/doudz/homeassistant-myjdownloader/blob/73168aca3b7ba0679bb281785e8d0ea53f6c7cc5/custom_components/myjdownloader/sensor.py#L209

to:

```python
    @property
    def extra_state_attributes(self):
        """Return the state attributes."""
        devices = sorted(self.devices.values(), key=lambda x: x.name)
        return {
            "jdownloaders": [device.name for device in devices],
            "jdownloader_ids": [device.device_id for device in devices],
        }
```

This allows people to create links directly to their current jdownloader instance.
for example in my single device use case:

```yaml
  - type: custom:button-card
    tap_action:
      action: url
      url_path: >
        [[[
          return 'https://my.jdownloader.org/?deviceId='+states['sensor.jdownloaders_online'].attributes.jdownloader_ids[0]+'#webinterface:downloads';
        ]]]
    name: JDownloader
    ...
```
