### ISSUE TITLE
[Feature request] Add credit of the 9kw Captcha Solver 

### ISSUE THREAD

**Issue by update-freak** [doudz/homeassistant-myjdownloader#39]
It would be great if the extionsion could get the credit of the 9kw Captcha Solver.
In the screenshot it's the 177.

![9kw](https://github.com/doudz/homeassistant-myjdownloader/assets/40196995/d5a4f177-bd4b-4d86-b38f-4e3f2c4a2809)

Idea: Send a messeage to smartphone when the credit is below 150.

**Comment by kymograph** [comment]
This can be easily achieved with the Rest sensor and the 9kw API. Its actually even cleaner to separate it from the JDownloader integration as it is a separate service.

See https://www.9kw.eu/api.html#apiaccount-tab for details

Simple example REST entry:

```
sensor:
  - platform: rest
    resource: https://www.9kw.eu/index.cgi?action=usercaptchaguthaben&apikey=<YOURAPIKEY>
    name: my-9kw-balance
    state_class: measurement
```
